spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/player_count
    username: postgres
    password: 0tterup1  # Replace with your actual password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

steam:
  api:
    base-url: https://api.steampowered.com
    key: 92EA7B3E6345EAE196691332AEFFAC69

logging:
  level:
    com.steamtracker: DEBUG